services:
  crm-server:
    image: crm-server:${VERSION}

    container_name: crm-server

    restart: unless-stopped

    env_file:
      - .env.prod

    ports:
      - "3000:3000"

networks:
  default:
    external: true
    name: crm-network
