const organizations = [
  {
    id: "1",
    parent: "Phòng Marketing",
    children: [
      { name: "Nhóm Facebook Ads", desc: "Chạy quảng cáo đa nền tảng" },
      { name: "Nhóm Content", desc: "Sản xuất nội dung media, bài viết" },
      { name: "Nhóm Design", desc: "Thiết kế ấn phẩm, banner, video" },
    ],
  },
  {
    id: "2",
    parent: "Phòng Sale",
    children: [
      {
        name: "Nhóm Sale Hà Nội",
        desc: "Telesale & chốt đơn khu vực miền Bắc",
      },
      { name: "Nhóm Sale HCM", desc: "Telesale & chốt đơn khu vực miền Nam" },
      {
        name: "Nhóm Sale Đà Nẵng",
        desc: "Telesale & chốt đơn khu vực miền Trung",
      },
    ],
  },
  {
    id: "3",
    parent: "Phòng Kỹ Thuật",
    children: [
      { name: "Nhóm Backend", desc: "Phát triển API và xử lý dữ liệu" },
      { name: "Nhóm Frontend", desc: "Phát triển giao diện người dùng" },
      { name: "Nhóm DevOps", desc: "Vận hành hạ tầng và CI/CD" },
    ],
  },
  {
    id: "4",
    parent: "Phòng Nhân Sự",
    children: [
      { name: "Nhóm Tuyển Dụng", desc: "Tìm kiếm và tuyển dụng nhân sự" },
      { name: "Nhóm Đào Tạo", desc: "Phát triển năng lực đội ngũ" },
    ],
  },
];

const leads = [
  {
    id: "LEAD001",
    name: "Nguyễn Văn Minh",
    avatar: "https://i.pravatar.cc/100?img=1",
    timeAgo: "10 phút trước",
    tags: ["Trial", "Vitamin"],
    assignee: { name: "Lê Văn A", avatar: "https://i.pravatar.cc/100?img=10" },
    status: "Biz tạo mới",
  },
  {
    id: "LEAD002",
    name: "Trần Thị Lan",
    avatar: "https://i.pravatar.cc/100?img=2",
    timeAgo: "25 phút trước",
    tags: ["Premium", "FPT"],
    assignee: {
      name: "Trần Văn B",
      avatar: "https://i.pravatar.cc/100?img=12",
    },
    status: "Biz tạo mới",
  },
  {
    id: "LEAD003",
    name: "Lê Hoàng Nam",
    avatar: "https://i.pravatar.cc/100?img=3",
    timeAgo: "1 giờ trước",
    tags: ["HOT"],
    assignee: { name: "Lê Văn A", avatar: "https://i.pravatar.cc/100?img=10" },
    status: "Biz tạo mới",
  },
  {
    id: "LEAD006",
    name: "Anh Tuấn",
    avatar: "https://i.pravatar.cc/100?img=6",
    timeAgo: "5 giờ trước",
    tags: ["HOT", "Tư vấn viên"],
    assignee: { name: "Lê Văn A", avatar: "https://i.pravatar.cc/100?img=10" },
    status: "Biz đã nhận gói cước",
  },
  {
    id: "LEAD011",
    name: "Lan Trinh",
    avatar: "https://i.pravatar.cc/100?img=9",
    timeAgo: "1 ngày trước",
    tags: ["Follow-up"],
    assignee: { name: "Lê Văn A", avatar: "https://i.pravatar.cc/100?img=10" },
    status: "Biz đã kết nối channel",
    actionNeeded: "Còn 2h",
    actionType: "green",
  },
  {
    id: "LEAD012",
    name: "Nguyễn Phương Hằng",
    avatar: "https://i.pravatar.cc/100?img=13",
    timeAgo: "2 ngày trước",
    tags: ["VIP"],
    assignee: {
      name: "Trần Văn B",
      avatar: "https://i.pravatar.cc/100?img=12",
    },
    status: "Biz đã kết nối channel",
  },
];

const tasks = [
  {
    id: "#09382",
    action: "Nhắc gia hạn gói cước",
    time: "15 phút nữa",
    timeType: "soon",
    customer: {
      name: "Phạm Tường Vy",
      avatar: "https://i.pravatar.cc/100?img=15",
      email: "vy.pham@example.com",
      phone: "0912 345 678",
    },
    platform: "SmaxAi",
    assignee: { name: "Hải Anh", avatar: "https://i.pravatar.cc/100?img=11" },
  },
  {
    id: "#09381",
    action: "Gọi điện tư vấn khoá học",
    time: "Đã trễ 10p",
    timeType: "late",
    customer: {
      name: "Nguyễn Văn An",
      avatar: "https://i.pravatar.cc/100?img=60",
      email: "an.nguyen@example.com",
      phone: "0988 765 432",
    },
    platform: "Appvn",
    assignee: { name: "Hải Anh", avatar: "https://i.pravatar.cc/100?img=11" },
  },
  {
    id: "#09380",
    action: "Gửi báo giá dự án",
    time: "1 giờ nữa",
    timeType: "soon",
    customer: {
      name: "Trần Minh Tâm",
      avatar: "https://i.pravatar.cc/100?img=20",
      email: "tam.tran@example.com",
      phone: "0905 123 456",
    },
    platform: "Botvn",
    assignee: { name: "Hải Anh", avatar: "https://i.pravatar.cc/100?img=11" },
  },
];

const customers = [
  {
    id: "CUST001",
    name: "Phạm Tường Vy",
    avatar: "https://i.pravatar.cc/100?img=15",
    type: "VIP Customer",
    email: "vy.pham@example.com",
    phone: "0912 345 678",
    biz: ["Torano", "Biluxury"],
    platforms: ["SmaxAi", "Botvn"],
    group: "Nhóm Sale Hà Nội",
    registeredAt: "10/10/2022",
    lastLoginAt: "30/03/2026",
    tags: ["#KHTiemNang"],
  },
  {
    id: "CUST002",
    name: "Nguyễn Văn An",
    avatar: "https://i.pravatar.cc/100?img=60",
    type: "Regular",
    email: "an.nguyen@example.com",
    phone: "0988 765 432",
    biz: ["FPT"],
    platforms: ["Appvn"],
    group: "Nhóm Content",
    registeredAt: "15/01/2023",
    lastLoginAt: "28/03/2026",
    tags: ["#NewUser"],
  },
  {
    id: "CUST003",
    name: "Trần Minh Tâm",
    avatar: "https://i.pravatar.cc/100?img=20",
    type: "Premium",
    email: "tam.tran@example.com",
    phone: "0905 123 456",
    biz: ["Viettel"],
    platforms: ["Botvn"],
    group: "Nhóm Sale HCM",
    registeredAt: "20/05/2022",
    lastLoginAt: "29/03/2026",
    tags: ["#Loyal"],
  },
  {
    id: "CUST004",
    name: "Lê Thị Hồng",
    avatar: "https://i.pravatar.cc/100?img=25",
    type: "Regular",
    email: "hong.le@example.com",
    phone: "0934 567 890",
    biz: ["Vinamilk"],
    platforms: ["SmaxAi"],
    group: "Nhóm Facebook Ads",
    registeredAt: "12/12/2023",
    lastLoginAt: "25/03/2026",
    tags: ["#Trial"],
  },
  {
    id: "CUST005",
    name: "Hoàng Văn Thái",
    avatar: "https://i.pravatar.cc/100?img=30",
    type: "VIP Customer",
    email: "thai.hoang@example.com",
    phone: "0977 111 222",
    biz: ["Masan"],
    platforms: ["Appvn"],
    group: "Nhóm DevOps",
    registeredAt: "05/03/2021",
    lastLoginAt: "30/03/2026",
    tags: ["#Whale"],
  },
];

const users = [
  {
    id: "USER001",
    name: "Chủ hệ thống CRM",
    email: "owner@crm.vn",
    password: "Owner@123",
    avatar: "https://i.pravatar.cc/100?img=33",
    department: [],
    group: [],
    phone: "0901 000 001",
    role: "OWNER",
  },
  {
    id: "USER002",
    name: "Quản trị CRM",
    email: "admin@crm.vn",
    password: "Admin@123",
    avatar: "https://i.pravatar.cc/100?img=47",
    department: ["Phòng Nhân Sự"],
    group: ["Nhóm Tuyển Dụng"],
    phone: "0901 000 002",
    role: "ADMIN",
  },
  {
    id: "USER003",
    name: "Phạm Thanh Sơn",
    email: "manager.sale@crm.vn",
    password: "Manager@123",
    avatar: "https://i.pravatar.cc/100?img=12",
    department: ["Phòng Sale"],
    group: ["Nhóm Sale Hà Nội"],
    phone: "0901 000 003",
    role: "MANAGER",
  },
  {
    id: "USER004",
    name: "Vũ Thu Phương",
    email: "staff1@crm.vn",
    password: "Staff@123",
    avatar: "https://i.pravatar.cc/100?img=25",
    department: ["Phòng Sale"],
    group: ["Nhóm Sale Hà Nội"],
    phone: "0901 000 004",
    role: "STAFF",
    managerId: "USER003",
  },
  {
    id: "USER005",
    name: "Trần Văn Hùng",
    email: "staff2@crm.vn",
    password: "Staff@123",
    avatar: "https://i.pravatar.cc/100?img=30",
    department: ["Phòng Sale"],
    group: ["Nhóm Sale Hà Nội"],
    phone: "0901 000 005",
    role: "STAFF",
    managerId: "USER003",
  },
];

const staffFunctions = [
  {
    id: "FUNC001",
    title: "Marketing",
    desc: "Quản lý các chiến dịch quảng cáo, tạo ra lượng leads đầu vào cho hệ thống. Chức năng này giúp phân tích lưu lượng và theo dõi sự thay đổi của người dùng.",
    type: "marketing",
  },
  {
    id: "FUNC002",
    title: "Sale (Bán hàng)",
    desc: "Tiếp nhận Lead từ Marketing, chăm sóc qua các trạng thái kịch bản và chốt sales. Đội Sale quản lý chu kỳ sống khách hàng.",
    type: "sale",
  },
  {
    id: "FUNC003",
    title: "Kỹ Thuật",
    desc: "Xây dựng, bảo trì và phát triển nền tảng CRM. Đảm bảo server ổn định, môi trường an toàn và xử lý backend tự động.",
    type: "tech",
  },
];

const events = [
  {
    id: "EVT001",
    name: "Đăng ký tài khoản mới",
    sub: "Hệ thống tự động",
    group: "user_moi",
    customer: { name: "Nguyễn Văn Minh", avatar: "https://i.pravatar.cc/100?img=1", role: "Giám đốc điều hành - Công ty TNHH ABC", email: "abc@company.com", phone: "0987 654 321", source: "Facebook Ads", address: "Tầng 3, Tòa nhà X, Quận 1, TP. HCM" },
    biz: { id: "#BIZ001", tags: ["Trial", "Vitamin"] },
    assignee: { name: "Lê Văn A", avatar: "https://i.pravatar.cc/100?img=10", role: "Nhân viên Sales" },
    stage: "Đăng ký thành công",
    tags: ["VIP", "Cần tư vấn sâu"],
    plan: { name: "PREMIUM", cycle: "Thanh toán theo tháng", price: "2.990.000 đ", daysLeft: 15, expiryDate: "15/04/2026" },
    services: [{ name: "Zalo OA Integration", active: true }, { name: "Livechat Support", active: true }],
    quotas: [{ name: "Truy cập User", used: 5, total: 10, color: "blue" }, { name: "Khối lượng Email", used: 8000, total: 10000, color: "red" }],
    timeline: [
      { type: "phone", title: "Lê Văn A đã gọi điện cho khách hàng", time: "10:00 Hôm nay", content: "Khách hàng đang rất quan tâm gói Premium.", duration: "05:20s" },
      { type: "email", title: "Hệ thống tự động gửi Email giới thiệu dịch vụ", time: "08:30 Hôm qua", content: null, duration: null },
      { type: "event", title: "Lead được tạo từ chiến dịch FB_Lead_Gen_2026", time: "08:00 Hôm qua", content: null, duration: null },
    ],
  },
  {
    id: "EVT002",
    name: "Xác minh email thành công",
    sub: "Xác minh tự động",
    group: "user_moi",
    customer: { name: "Trần Thị Lan", avatar: "https://i.pravatar.cc/100?img=5", role: "Khách hàng", email: "lan.tran@email.com", phone: "0912 345 678", source: "Google Ads", address: "TP. Hà Nội" },
    biz: { id: "#BIZ002", tags: ["Premium", "FPT"] },
    assignee: { name: "Trần Văn B", avatar: "https://i.pravatar.cc/100?img=12", role: "Nhân viên Sales" },
    stage: "Xác minh thành công",
    tags: ["Premium"],
    plan: { name: "PREMIUM", cycle: "Thanh toán theo tháng", price: "2.990.000 đ", daysLeft: 25, expiryDate: "25/04/2026" },
    services: [{ name: "Livechat Support", active: true }],
    quotas: [{ name: "Truy cập User", used: 3, total: 10, color: "blue" }],
    timeline: [{ type: "event", title: "Email xác minh hoàn tất", time: "08:55 Hôm nay", content: null, duration: null }],
  },
  {
    id: "EVT003",
    name: "Hoàn tất hồ sơ cá nhân",
    sub: "Người dùng tự thao tác",
    group: "user_moi",
    customer: { name: "Lê Hoàng Nam", avatar: "https://i.pravatar.cc/100?img=8", role: "Khách hàng", email: "nam.le@email.com", phone: "0933 111 222", source: "Referral", address: "TP. Đà Nẵng" },
    biz: { id: "#BIZ003", tags: ["Basic", "VietinBank"] },
    assignee: { name: "Nguyễn Văn C", avatar: "https://i.pravatar.cc/100?img=13", role: "Nhân viên Sales" },
    stage: "Đã hoàn tất",
    tags: ["Basic"],
    plan: { name: "BASIC", cycle: "Thanh toán theo tháng", price: "990.000 đ", daysLeft: 20, expiryDate: "20/04/2026" },
    services: [{ name: "Livechat Support", active: true }],
    quotas: [{ name: "Truy cập User", used: 2, total: 5, color: "blue" }],
    timeline: [{ type: "event", title: "Hồ sơ cá nhân đã hoàn tất", time: "08:00 Hôm nay", content: null, duration: null }],
  },
  {
    id: "EVT004",
    name: "Đăng nhập lần đầu",
    sub: "Hệ thống ghi nhận",
    group: "user_moi",
    customer: { name: "Phạm Quốc Huy", avatar: "https://i.pravatar.cc/100?img=15", role: "Khách hàng", email: "huy.pham@email.com", phone: "0944 222 333", source: "Direct", address: "TP. HCM" },
    biz: { id: "#BIZ004", tags: ["Enterprise", "Viettel"] },
    assignee: { name: "Phạm Thị D", avatar: "https://i.pravatar.cc/100?img=14", role: "Nhân viên Sales" },
    stage: "Đã đăng nhập",
    tags: ["Enterprise"],
    plan: { name: "ENTERPRISE", cycle: "Thanh toán theo năm", price: "19.990.000 đ", daysLeft: 180, expiryDate: "15/10/2026" },
    services: [{ name: "Zalo OA Integration", active: true }, { name: "Livechat Support", active: true }],
    quotas: [{ name: "Truy cập User", used: 1, total: 50, color: "blue" }],
    timeline: [{ type: "event", title: "Đăng nhập lần đầu từ Chrome / Windows", time: "07:30 Hôm nay", content: null, duration: null }],
  },
  {
    id: "EVT005",
    name: "Thêm phương thức thanh toán",
    sub: "Người dùng tự thao tác",
    group: "user_moi",
    customer: { name: "Vũ Thị Mai", avatar: "https://i.pravatar.cc/100?img=20", role: "Khách hàng", email: "mai.vu@email.com", phone: "0955 333 444", source: "Facebook", address: "TP. HCM" },
    biz: { id: "#BIZ005", tags: ["Standard", "BIDV"] },
    assignee: { name: "Lê Văn A", avatar: "https://i.pravatar.cc/100?img=10", role: "Nhân viên Sales" },
    stage: "Thêm thành công",
    tags: ["Standard"],
    plan: { name: "TRIAL", cycle: "Dùng thử", price: "0 đ", daysLeft: 7, expiryDate: "09/04/2026" },
    services: [],
    quotas: [{ name: "Truy cập User", used: 1, total: 3, color: "blue" }],
    timeline: [{ type: "event", title: "Thêm phương thức thanh toán BIDV", time: "06:30 Hôm nay", content: null, duration: null }],
  },
  {
    id: "EVT006",
    name: "Tạo doanh nghiệp thành công",
    sub: "Hệ thống tự động",
    group: "biz_moi",
    customer: { name: "Hoàng Sơn", avatar: "https://i.pravatar.cc/100?img=7", role: "CEO - Hoàng Sơn Corp", email: "son.hoang@email.com", phone: "0966 444 555", source: "Facebook", address: "TP. HCM" },
    biz: { id: "#BIZ006", tags: ["Trial", "FB"] },
    assignee: { name: "Nguyễn Văn C", avatar: "https://i.pravatar.cc/100?img=13", role: "Nhân viên Sales" },
    stage: "Tạo biz thành công",
    tags: ["Trial"],
    plan: { name: "TRIAL", cycle: "Dùng thử", price: "0 đ", daysLeft: 14, expiryDate: "16/04/2026" },
    services: [],
    quotas: [{ name: "Truy cập User", used: 1, total: 3, color: "blue" }],
    timeline: [{ type: "event", title: "Biz được tạo tự động", time: "09:05 Hôm nay", content: null, duration: null }],
  },
  {
    id: "EVT007",
    name: "Kết nối kênh chat đầu tiên",
    sub: "Tự động kích hoạt",
    group: "biz_moi",
    customer: { name: "Minh Anh", avatar: "https://i.pravatar.cc/100?img=25", role: "Khách hàng", email: "anh.minh@email.com", phone: "0977 555 666", source: "Zalo", address: "TP. Hà Nội" },
    biz: { id: "#BIZ007", tags: ["HOT", "Zalo"] },
    assignee: { name: "Lê Văn A", avatar: "https://i.pravatar.cc/100?img=10", role: "Nhân viên Sales" },
    stage: "Kết nối thành công",
    tags: ["HOT"],
    plan: { name: "BASIC", cycle: "Thanh toán theo tháng", price: "990.000 đ", daysLeft: 28, expiryDate: "28/04/2026" },
    services: [{ name: "Zalo OA Integration", active: true }],
    quotas: [{ name: "Truy cập User", used: 2, total: 5, color: "blue" }],
    timeline: [{ type: "event", title: "Kết nối Zalo OA thành công", time: "08:50 Hôm nay", content: null, duration: null }],
  },
  {
    id: "EVT008",
    name: "Thêm nhân viên đầu tiên",
    sub: "Admin thao tác",
    group: "biz_moi",
    customer: { name: "Bảo Quốc", avatar: "https://i.pravatar.cc/100?img=33", role: "Khách hàng", email: "quoc.bao@email.com", phone: "0988 666 777", source: "Referral", address: "TP. HCM" },
    biz: { id: "#BIZ008", tags: ["Báo giá", "VPBank"] },
    assignee: { name: "Trần Văn B", avatar: "https://i.pravatar.cc/100?img=12", role: "Nhân viên Sales" },
    stage: "Thêm thành công",
    tags: ["Báo giá"],
    plan: { name: "PREMIUM", cycle: "Thanh toán theo tháng", price: "2.990.000 đ", daysLeft: 22, expiryDate: "22/04/2026" },
    services: [{ name: "Livechat Support", active: true }],
    quotas: [{ name: "Truy cập User", used: 3, total: 10, color: "blue" }],
    timeline: [{ type: "event", title: "Thêm nhân viên mới vào hệ thống", time: "08:35 Hôm nay", content: null, duration: null }],
  },
  {
    id: "EVT009",
    name: "Cấu hình tên miền riêng",
    sub: "Admin thao tác",
    group: "biz_moi",
    customer: { name: "Thanh Hằng", avatar: "https://i.pravatar.cc/100?img=27", role: "Khách hàng", email: "hang.thanh@email.com", phone: "0999 777 888", source: "Direct", address: "TP. HCM" },
    biz: { id: "#BIZ009", tags: ["Premium", "Sacombank"] },
    assignee: { name: "Nguyễn Văn C", avatar: "https://i.pravatar.cc/100?img=13", role: "Nhân viên Sales" },
    stage: "Cấu hình thành công",
    tags: ["Premium"],
    plan: { name: "PREMIUM", cycle: "Thanh toán theo tháng", price: "2.990.000 đ", daysLeft: 18, expiryDate: "18/04/2026" },
    services: [{ name: "Zalo OA Integration", active: true }, { name: "Livechat Support", active: true }],
    quotas: [{ name: "Truy cập User", used: 5, total: 10, color: "blue" }],
    timeline: [{ type: "event", title: "Cấu hình tên miền riêng thành công", time: "08:00 Hôm nay", content: null, duration: null }],
  },
  {
    id: "EVT010",
    name: "Dung lượng lưu trữ sắp đầy",
    sub: "Cảnh báo tự động",
    group: "can_nang_cap",
    customer: { name: "Đức Phúc", avatar: "https://i.pravatar.cc/100?img=51", role: "Khách hàng", email: "phuc.duc@email.com", phone: "0900 888 999", source: "Direct", address: "TP. HCM" },
    biz: { id: "#BIZ010", tags: ["Enterprise", "VPBank"] },
    assignee: { name: "Lê Văn A", avatar: "https://i.pravatar.cc/100?img=10", role: "Nhân viên Sales" },
    stage: "Cảnh báo nâng cấp",
    tags: ["Enterprise"],
    plan: { name: "BASIC", cycle: "Thanh toán theo tháng", price: "990.000 đ", daysLeft: 10, expiryDate: "12/04/2026" },
    services: [{ name: "Livechat Support", active: true }],
    quotas: [{ name: "Truy cập User", used: 4, total: 5, color: "orange" }, { name: "Dung lượng", used: 900, total: 1000, color: "red" }],
    timeline: [{ type: "event", title: "Cảnh báo dung lượng lưu trữ đạt 90%", time: "09:00 Hôm nay", content: null, duration: null }],
  },
  {
    id: "EVT011",
    name: "Hết hạn gói Trial",
    sub: "Hệ thống gửi thông báo",
    group: "can_nang_cap",
    customer: { name: "Hương Giang", avatar: "https://i.pravatar.cc/100?img=44", role: "Khách hàng", email: "giang.huong@email.com", phone: "0911 999 000", source: "Shopee", address: "TP. HCM" },
    biz: { id: "#BIZ011", tags: ["Trial", "Shopee"] },
    assignee: { name: "Trần Văn B", avatar: "https://i.pravatar.cc/100?img=12", role: "Nhân viên Sales" },
    stage: "Hết hạn Trial",
    tags: ["Trial"],
    plan: { name: "TRIAL", cycle: "Dùng thử", price: "0 đ", daysLeft: 0, expiryDate: "02/04/2026" },
    services: [],
    quotas: [{ name: "Truy cập User", used: 3, total: 3, color: "red" }],
    timeline: [{ type: "event", title: "Gói Trial đã hết hạn", time: "08:30 Hôm nay", content: null, duration: null }],
  },
  {
    id: "EVT012",
    name: "Yêu cầu nâng cấp gói",
    sub: "Khách hàng yêu cầu",
    group: "can_nang_cap",
    customer: { name: "Minh Đức", avatar: "https://i.pravatar.cc/100?img=59", role: "Khách hàng", email: "duc.minh@email.com", phone: "0922 000 111", source: "MoMo", address: "TP. Hà Nội" },
    biz: { id: "#BIZ012", tags: ["Basic", "MoMo"] },
    assignee: { name: "Nguyễn Văn C", avatar: "https://i.pravatar.cc/100?img=13", role: "Nhân viên Sales" },
    stage: "Yêu cầu xử lý",
    tags: ["Basic"],
    plan: { name: "BASIC", cycle: "Thanh toán theo tháng", price: "990.000 đ", daysLeft: 5, expiryDate: "07/04/2026" },
    services: [{ name: "Livechat Support", active: true }],
    quotas: [{ name: "Truy cập User", used: 4, total: 5, color: "orange" }],
    timeline: [{ type: "phone", title: "Khách hàng gọi yêu cầu nâng cấp", time: "07:30 Hôm nay", content: "Muốn nâng cấp lên Premium", duration: "03:15s" }],
  },
  {
    id: "EVT013",
    name: "Nâng cấp thành công",
    sub: "Thanh toán thành công",
    group: "can_nang_cap",
    customer: { name: "Thanh Mai", avatar: "https://i.pravatar.cc/100?img=47", role: "Khách hàng", email: "mai.thanh@email.com", phone: "0933 111 222", source: "ZaloPay", address: "TP. HCM" },
    biz: { id: "#BIZ013", tags: ["Premium", "ZaloPay"] },
    assignee: { name: "Lê Văn A", avatar: "https://i.pravatar.cc/100?img=10", role: "Nhân viên Sales" },
    stage: "Đã nâng cấp",
    tags: ["Premium"],
    plan: { name: "PREMIUM", cycle: "Thanh toán theo tháng", price: "2.990.000 đ", daysLeft: 30, expiryDate: "02/05/2026" },
    services: [{ name: "Zalo OA Integration", active: true }, { name: "Livechat Support", active: true }],
    quotas: [{ name: "Truy cập User", used: 3, total: 10, color: "blue" }],
    timeline: [{ type: "event", title: "Nâng cấp từ Basic lên Premium thành công", time: "06:30 Hôm nay", content: null, duration: null }],
  },
  {
    id: "EVT014",
    name: "Gói cước sắp hết hạn trong 7 ngày",
    sub: "Thông báo tự động",
    group: "sap_het_han",
    customer: { name: "Anh Tuấn", avatar: "https://i.pravatar.cc/100?img=5", role: "Khách hàng", email: "tuan.anh@email.com", phone: "0944 222 333", source: "Direct", address: "TP. Hà Nội" },
    biz: { id: "#BIZ014", tags: ["HOT", "Tư vấn viên"] },
    assignee: { name: "Lê Văn A", avatar: "https://i.pravatar.cc/100?img=10", role: "Nhân viên Sales" },
    stage: "Còn 7 ngày",
    tags: ["HOT"],
    plan: { name: "PREMIUM", cycle: "Thanh toán theo tháng", price: "2.990.000 đ", daysLeft: 7, expiryDate: "09/04/2026" },
    services: [{ name: "Livechat Support", active: true }],
    quotas: [{ name: "Truy cập User", used: 7, total: 10, color: "orange" }],
    timeline: [{ type: "event", title: "Thông báo sắp hết hạn gói cước", time: "08:50 Hôm nay", content: null, duration: null }],
  },
  {
    id: "EVT015",
    name: "Gói cước sắp hết hạn trong 3 ngày",
    sub: "Cảnh báo khẩn cấp",
    group: "sap_het_han",
    customer: { name: "Hoàng Bảo", avatar: "https://i.pravatar.cc/100?img=17", role: "Khách hàng", email: "bao.hoang@email.com", phone: "0955 333 444", source: "TikTok", address: "TP. HCM" },
    biz: { id: "#BIZ015", tags: ["Premium", "TikTok"] },
    assignee: { name: "Trần Văn B", avatar: "https://i.pravatar.cc/100?img=12", role: "Nhân viên Sales" },
    stage: "Còn 3 ngày",
    tags: ["Premium"],
    plan: { name: "PREMIUM", cycle: "Thanh toán theo tháng", price: "2.990.000 đ", daysLeft: 3, expiryDate: "05/04/2026" },
    services: [{ name: "Livechat Support", active: true }],
    quotas: [{ name: "Truy cập User", used: 8, total: 10, color: "red" }],
    timeline: [{ type: "event", title: "Cảnh báo khẩn cấp - còn 3 ngày", time: "08:30 Hôm nay", content: null, duration: null }],
  },
  {
    id: "EVT016",
    name: "Gói cước sắp hết hạn trong 1 ngày",
    sub: "Thông báo cuối cùng",
    group: "sap_het_han",
    customer: { name: "Phương Linh", avatar: "https://i.pravatar.cc/100?img=38", role: "Khách hàng", email: "linh.phuong@email.com", phone: "0966 444 555", source: "Haravan", address: "TP. Đà Nẵng" },
    biz: { id: "#BIZ016", tags: ["Standard", "Haravan"] },
    assignee: { name: "Trần Văn B", avatar: "https://i.pravatar.cc/100?img=12", role: "Nhân viên Sales" },
    stage: "Còn 1 ngày",
    tags: ["Standard"],
    plan: { name: "BASIC", cycle: "Thanh toán theo tháng", price: "990.000 đ", daysLeft: 1, expiryDate: "03/04/2026" },
    services: [{ name: "Livechat Support", active: true }],
    quotas: [{ name: "Truy cập User", used: 5, total: 5, color: "red" }],
    timeline: [{ type: "event", title: "Thông báo cuối cùng trước khi hết hạn", time: "07:30 Hôm nay", content: null, duration: null }],
  },
  {
    id: "EVT017",
    name: "Gia hạn thành công",
    sub: "Thanh toán qua chuyển khoản",
    group: "sap_het_han",
    customer: { name: "Quang Minh", avatar: "https://i.pravatar.cc/100?img=55", role: "Khách hàng", email: "minh.quang@email.com", phone: "0977 555 666", source: "Lazada", address: "TP. HCM" },
    biz: { id: "#BIZ017", tags: ["Enterprise", "Lazada"] },
    assignee: { name: "Nguyễn Văn C", avatar: "https://i.pravatar.cc/100?img=13", role: "Nhân viên Sales" },
    stage: "Đã gia hạn",
    tags: ["Enterprise"],
    plan: { name: "ENTERPRISE", cycle: "Thanh toán theo năm", price: "19.990.000 đ", daysLeft: 365, expiryDate: "02/04/2027" },
    services: [{ name: "Zalo OA Integration", active: true }, { name: "Livechat Support", active: true }],
    quotas: [{ name: "Truy cập User", used: 10, total: 50, color: "blue" }],
    timeline: [{ type: "event", title: "Gia hạn thành công qua chuyển khoản", time: "05:30 Hôm nay", content: null, duration: null }],
  },
  {
    id: "EVT018",
    name: "Thanh toán chuyển khoản mới",
    sub: "Đơn hàng #DH2026-001",
    group: "chuyen_khoan",
    customer: { name: "Thu Hà", avatar: "https://i.pravatar.cc/100?img=60", role: "Khách hàng", email: "ha.thu@email.com", phone: "0988 666 777", source: "Direct", address: "TP. HCM" },
    biz: { id: "#BIZ018", tags: ["Premium", "VCB"] },
    assignee: { name: "Lê Văn A", avatar: "https://i.pravatar.cc/100?img=10", role: "Nhân viên Sales" },
    stage: "Chờ xác nhận",
    tags: ["Premium"],
    plan: { name: "PREMIUM", cycle: "Thanh toán theo tháng", price: "2.990.000 đ", daysLeft: 30, expiryDate: "02/05/2026" },
    services: [{ name: "Livechat Support", active: true }],
    quotas: [{ name: "Truy cập User", used: 5, total: 10, color: "blue" }],
    timeline: [{ type: "event", title: "Nhận thanh toán chuyển khoản mới", time: "09:15 Hôm nay", content: null, duration: null }],
  },
  {
    id: "EVT019",
    name: "Xác nhận thanh toán thành công",
    sub: "Đơn hàng #DH2026-002",
    group: "chuyen_khoan",
    customer: { name: "Minh Khôi", avatar: "https://i.pravatar.cc/100?img=62", role: "Khách hàng", email: "khoi.minh@email.com", phone: "0999 777 888", source: "TPBank", address: "TP. Hà Nội" },
    biz: { id: "#BIZ019", tags: ["Enterprise", "TPBank"] },
    assignee: { name: "Trần Văn B", avatar: "https://i.pravatar.cc/100?img=12", role: "Nhân viên Sales" },
    stage: "Đã xác nhận",
    tags: ["Enterprise"],
    plan: { name: "ENTERPRISE", cycle: "Thanh toán theo năm", price: "19.990.000 đ", daysLeft: 365, expiryDate: "02/04/2027" },
    services: [{ name: "Zalo OA Integration", active: true }, { name: "Livechat Support", active: true }],
    quotas: [{ name: "Truy cập User", used: 15, total: 50, color: "blue" }],
    timeline: [{ type: "event", title: "Xác nhận thanh toán thành công", time: "08:00 Hôm nay", content: null, duration: null }],
  },
  {
    id: "EVT020",
    name: "Thanh toán thất bại - Sai số tài khoản",
    sub: "Đơn hàng #DH2026-003",
    group: "chuyen_khoan",
    customer: { name: "Lan Phương", avatar: "https://i.pravatar.cc/100?img=65", role: "Khách hàng", email: "phuong.lan@email.com", phone: "0900 888 999", source: "ACB", address: "TP. HCM" },
    biz: { id: "#BIZ020", tags: ["Standard", "ACB"] },
    assignee: { name: "Nguyễn Văn C", avatar: "https://i.pravatar.cc/100?img=13", role: "Nhân viên Sales" },
    stage: "Thanh toán lỗi",
    tags: ["Standard"],
    plan: { name: "BASIC", cycle: "Thanh toán theo tháng", price: "990.000 đ", daysLeft: 15, expiryDate: "17/04/2026" },
    services: [{ name: "Livechat Support", active: true }],
    quotas: [{ name: "Truy cập User", used: 3, total: 5, color: "orange" }],
    timeline: [{ type: "event", title: "Thanh toán thất bại - sai số tài khoản", time: "07:30 Hôm nay", content: "Số tài khoản không đúng, cần liên hệ lại khách hàng để xác nhận.", duration: null }],
  },
];

module.exports = {
  organizations,
  leads,
  tasks,
  customers,
  users,
  staffFunctions,
  events,
};
