const organizations = [
  {
    id: "1",
    parent: "Phòng Marketing",
    children: [
      { name: "Nhóm Facebook Ads", desc: "Chạy quảng cáo đa nền tảng" },
      { name: "Nhóm Content", desc: "Sản xuất nội dung media, bài viết" },
      { name: "Nhóm Design", desc: "Thiết kế ấn phẩm, banner, video" },
    ],
  },
  {
    id: "2",
    parent: "Phòng Sale",
    children: [
      {
        name: "Nhóm Sale Hà Nội",
        desc: "Telesale & chốt đơn khu vực miền Bắc",
      },
      { name: "Nhóm Sale HCM", desc: "Telesale & chốt đơn khu vực miền Nam" },
      {
        name: "Nhóm Sale Đà Nẵng",
        desc: "Telesale & chốt đơn khu vực miền Trung",
      },
    ],
  },
  {
    id: "3",
    parent: "Phòng Kỹ Thuật",
    children: [
      { name: "Nhóm Backend", desc: "Phát triển API và xử lý dữ liệu" },
      { name: "Nhóm Frontend", desc: "Phát triển giao diện người dùng" },
      { name: "Nhóm DevOps", desc: "Vận hành hạ tầng và CI/CD" },
    ],
  },
  {
    id: "4",
    parent: "Phòng Nhân Sự",
    children: [
      { name: "Nhóm Tuyển Dụng", desc: "Tìm kiếm và tuyển dụng nhân sự" },
      { name: "Nhóm Đào Tạo", desc: "Phát triển năng lực đội ngũ" },
    ],
  },
];

const leads = [
  {
    id: "LEAD001",
    name: "Nguyễn Văn Minh",
    avatar: "https://i.pravatar.cc/100?img=1",
    timeAgo: "10 phút trước",
    tags: ["Trial", "Vitamin"],
    assignee: { name: "Lê Văn A", avatar: "https://i.pravatar.cc/100?img=10" },
    status: "Biz tạo mới",
  },
  {
    id: "LEAD002",
    name: "Trần Thị Lan",
    avatar: "https://i.pravatar.cc/100?img=2",
    timeAgo: "25 phút trước",
    tags: ["Premium", "FPT"],
    assignee: {
      name: "Trần Văn B",
      avatar: "https://i.pravatar.cc/100?img=12",
    },
    status: "Biz tạo mới",
  },
  {
    id: "LEAD003",
    name: "Lê Hoàng Nam",
    avatar: "https://i.pravatar.cc/100?img=3",
    timeAgo: "1 giờ trước",
    tags: ["HOT"],
    assignee: { name: "Lê Văn A", avatar: "https://i.pravatar.cc/100?img=10" },
    status: "Biz tạo mới",
  },
  {
    id: "LEAD006",
    name: "Anh Tuấn",
    avatar: "https://i.pravatar.cc/100?img=6",
    timeAgo: "5 giờ trước",
    tags: ["HOT", "Tư vấn viên"],
    assignee: { name: "Lê Văn A", avatar: "https://i.pravatar.cc/100?img=10" },
    status: "Biz đã nhận gói cước",
  },
  {
    id: "LEAD011",
    name: "Lan Trinh",
    avatar: "https://i.pravatar.cc/100?img=9",
    timeAgo: "1 ngày trước",
    tags: ["Follow-up"],
    assignee: { name: "Lê Văn A", avatar: "https://i.pravatar.cc/100?img=10" },
    status: "Biz đã kết nối channel",
    actionNeeded: "Còn 2h",
    actionType: "green",
  },
  {
    id: "LEAD012",
    name: "Nguyễn Phương Hằng",
    avatar: "https://i.pravatar.cc/100?img=13",
    timeAgo: "2 ngày trước",
    tags: ["VIP"],
    assignee: {
      name: "Trần Văn B",
      avatar: "https://i.pravatar.cc/100?img=12",
    },
    status: "Biz đã kết nối channel",
  },
];

const tasks = [
  {
    id: "#09382",
    action: "Nhắc gia hạn gói cước",
    time: "15 phút nữa",
    timeType: "soon",
    customer: {
      name: "Phạm Tường Vy",
      avatar: "https://i.pravatar.cc/100?img=15",
      email: "vy.pham@example.com",
      phone: "0912 345 678",
    },
    platform: "SmaxAi",
    assignee: { name: "Hải Anh", avatar: "https://i.pravatar.cc/100?img=11" },
  },
  {
    id: "#09381",
    action: "Gọi điện tư vấn khoá học",
    time: "Đã trễ 10p",
    timeType: "late",
    customer: {
      name: "Nguyễn Văn An",
      avatar: "https://i.pravatar.cc/100?img=60",
      email: "an.nguyen@example.com",
      phone: "0988 765 432",
    },
    platform: "Appvn",
    assignee: { name: "Hải Anh", avatar: "https://i.pravatar.cc/100?img=11" },
  },
  {
    id: "#09380",
    action: "Gửi báo giá dự án",
    time: "1 giờ nữa",
    timeType: "soon",
    customer: {
      name: "Trần Minh Tâm",
      avatar: "https://i.pravatar.cc/100?img=20",
      email: "tam.tran@example.com",
      phone: "0905 123 456",
    },
    platform: "Botvn",
    assignee: { name: "Hải Anh", avatar: "https://i.pravatar.cc/100?img=11" },
  },
];

const customers = [
  {
    id: "CUST001",
    name: "Phạm Tường Vy",
    avatar: "https://i.pravatar.cc/100?img=15",
    type: "VIP Customer",
    email: "vy.pham@example.com",
    phone: "0912 345 678",
    biz: ["Torano", "Biluxury"],
    platforms: ["SmaxAi", "Botvn"],
    group: "Nhóm Sale Hà Nội",
    registeredAt: "10/10/2022",
    lastLoginAt: "30/03/2026",
    tags: ["#KHTiemNang"],
  },
  {
    id: "CUST002",
    name: "Nguyễn Văn An",
    avatar: "https://i.pravatar.cc/100?img=60",
    type: "Regular",
    email: "an.nguyen@example.com",
    phone: "0988 765 432",
    biz: ["FPT"],
    platforms: ["Appvn"],
    group: "Nhóm Content",
    registeredAt: "15/01/2023",
    lastLoginAt: "28/03/2026",
    tags: ["#NewUser"],
  },
  {
    id: "CUST003",
    name: "Trần Minh Tâm",
    avatar: "https://i.pravatar.cc/100?img=20",
    type: "Premium",
    email: "tam.tran@example.com",
    phone: "0905 123 456",
    biz: ["Viettel"],
    platforms: ["Botvn"],
    group: "Nhóm Sale HCM",
    registeredAt: "20/05/2022",
    lastLoginAt: "29/03/2026",
    tags: ["#Loyal"],
  },
  {
    id: "CUST004",
    name: "Lê Thị Hồng",
    avatar: "https://i.pravatar.cc/100?img=25",
    type: "Regular",
    email: "hong.le@example.com",
    phone: "0934 567 890",
    biz: ["Vinamilk"],
    platforms: ["SmaxAi"],
    group: "Nhóm Facebook Ads",
    registeredAt: "12/12/2023",
    lastLoginAt: "25/03/2026",
    tags: ["#Trial"],
  },
  {
    id: "CUST005",
    name: "Hoàng Văn Thái",
    avatar: "https://i.pravatar.cc/100?img=30",
    type: "VIP Customer",
    email: "thai.hoang@example.com",
    phone: "0977 111 222",
    biz: ["Masan"],
    platforms: ["Appvn"],
    group: "Nhóm DevOps",
    registeredAt: "05/03/2021",
    lastLoginAt: "30/03/2026",
    tags: ["#Whale"],
  },
];

const staff = [
  {
    id: "STAFF001",
    name: "Phạm Thanh Sơn",
    email: "son.pham@crm.vn",
    avatar: "https://i.pravatar.cc/100?img=33",
    department: ["Phòng Sale", "Phòng Marketing"],
    group: ["Nhóm Sale Hà Nội"],
    phone: "0901 234 567",
    role: "Trưởng phòng",
  },
  {
    id: "STAFF002",
    name: "Vũ Thu Phương",
    email: "phuong.vu@crm.vn",
    avatar: "https://i.pravatar.cc/100?img=47",
    department: ["Phòng Marketing"],
    group: ["Nhóm Content"],
    phone: "0912 345 678",
    role: "Nhân viên",
  },
  {
    id: "STAFF003",
    name: "Nguyễn Hoàng Nam",
    email: "nam.nguyen@crm.vn",
    avatar: "https://i.pravatar.cc/100?img=12",
    department: ["Phòng Kỹ Thuật"],
    group: ["Nhóm Backend"],
    phone: "0922 333 444",
    role: "Nhân viên",
  },
  {
    id: "STAFF004",
    name: "Lê Thị Mai",
    email: "mai.le@crm.vn",
    avatar: "https://i.pravatar.cc/100?img=25",
    department: ["Phòng Nhân Sự"],
    group: ["Nhóm Tuyển Dụng"],
    phone: "0933 444 555",
    role: "Nhân viên",
  },
  {
    id: "STAFF005",
    name: "Trần Văn Hùng",
    email: "hung.tran@crm.vn",
    avatar: "https://i.pravatar.cc/100?img=30",
    department: ["Phòng Sale"],
    group: ["Nhóm Sale HCM"],
    phone: "0944 555 666",
    role: "Nhân viên",
  },
];

const staffFunctions = [
  {
    id: "FUNC001",
    title: "Marketing",
    desc: "Quản lý các chiến dịch quảng cáo, tạo ra lượng leads đầu vào cho hệ thống. Chức năng này giúp phân tích lưu lượng và theo dõi sự thay đổi của người dùng.",
    type: "marketing",
  },
  {
    id: "FUNC002",
    title: "Sale (Bán hàng)",
    desc: "Tiếp nhận Lead từ Marketing, chăm sóc qua các trạng thái kịch bản và chốt sales. Đội Sale quản lý chu kỳ sống khách hàng.",
    type: "sale",
  },
  {
    id: "FUNC003",
    title: "Kỹ Thuật",
    desc: "Xây dựng, bảo trì và phát triển nền tảng CRM. Đảm bảo server ổn định, môi trường an toàn và xử lý backend tự động.",
    type: "tech",
  },
];

module.exports = {
  organizations,
  leads,
  tasks,
  customers,
  staff,
  staffFunctions,
};
