const COURSE_CHALLENGE_TYPE = {
  FIXED_DATE: "fixed_date",
  ROLLING: "rolling",
};

const CHALLENGE_DAY_STATUS = {
  LOCKED: "LOCKED",
  COMPLETED: "COMPLETED",
  OVERDUE: "OVERDUE",
  OPEN: "OPEN",
};

module.exports = {
  COURSE_CHALLENGE_TYPE,
  CHALLENGE_DAY_STATUS,
};
