version: '3.9'

services:
  redis:
    image: redis:7-alpine
    container_name: redis
    restart: always
    ports:
      - "6379:6379"
    command:
      [
        "redis-server",
        "--appendonly", "yes",
        "--maxmemory", "256mb",
        "--maxmemory-policy", "allkeys-lru",
        "--user", "admin", "on", ">cw82oKff2mU1RxDpIssDd7FKK7v", "~*", "+@all"
      ]
    volumes:
      - redis_data:/data

volumes:
  redis_data: