# Bảo mật
requirepass my_super_secret_password
# Tạo thêm user cụ thể (ACL - Access Control List)
# User: dev_user, Pass: dev_password, Full quyền trên các key bắt đầu bằng 'cache:'
user dev_user on >dev_password ~cache:* +@all

# Hiệu năng & Bộ nhớ
maxmemory 512mb
maxmemory-policy allkeys-lru

# Lưu trữ dữ liệu (Persistence)
appendonly yes
appendfilename "appendonly.aof"